---

### Generic smell configuration
detectors:
  # You can disable smells completely
  IrresponsibleModule:
    enabled: false
  MissingSafeMethod:
    enabled: false
  UncommunicativeModuleName:
    enabled: false

